spring:
  datasource:
    url: jdbc:mysql://27.96.134.111:3306/coupang?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: coupang1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    session:
      host: 118.67.132.101
      port: 6379
      password:
    cache:
      host: 118.67.132.101
      port: 6380
      password:

mybatis:
  type-aliases-package: com.coupang.marketplace.*.domain
  mapper-locations: mybatis/mapper/**/*.xml

ncp:
  object-storage:
    end-point: https://kr.object.ncloudstorage.com
    region-name: kr-standard
    access-key: 3af1ocT3MbklqvdAL0Ij
    secret-key: yYZP9p3FgI4RE2VG2akDSd4AxOOMUkOFc1TEKGc7
    bucket-name: review-images